@startuml Use Case Diagram

left to right direction

package Services {
    actor FileStorage
    FileStorage as "Amazon AWS S3" << service >>
}

package ApplicationUseCases {
    usecase commonActions as "Browse items
        __
        Search items"
    usecase items as "Add/Edit Item
        __
        Add/Edit Category"

    usecase authorizedActions as "Cart
        __
        Process payments"
    usecase auth as "Login
        __
        Register"
}

package Users {
    actor AnonymousUser
    AnonymousUser as "Anonymous User"

    actor AuthenticatedUser
    AuthenticatedUser as "Authenticated User"

    actor Administrator
    Administrator as "Administrator"
}

items --- FileStorage
commonActions ---FileStorage

AnonymousUser --> auth
AnonymousUser --> commonActions

AuthenticatedUser --> commonActions
AuthenticatedUser --> authorizedActions

Administrator --> commonActions
Administrator --> authorizedActions
Administrator --> items

@enduml